# Generated by Django 4.2.3 on 2023-09-20 18:24

from django.db import migrations, models
import video_analyzer.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analyzer', '0004_alter_video_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=video_analyzer.models.audio_directory_path),
        ),
    ]
