# Generated by Django 4.2.3 on 2023-09-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analyzer', '0005_alter_video_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='whisper_summary_translate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='whisper_transcribe_translate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
